chirun_lti/urls.py
from   django.conf import settings
from   django.conf.urls.static import static
from   django.contrib import admin
from   django.urls import path, include
from   django.utils.translation import gettext_lazy as _
import lti.views

urlpatterns = [
    path('', lti.views.IndexView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path('lti/', include('lti.urls', namespace='lti')),
    path('material/', include('material.urls', namespace='material')),
]

admin.site.site_header = admin.site.site_title = admin.site.index_title = _('Chirun LTI Administration')

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lti/urls.py
from . import views
from django.urls import path, include

app_name = 'lti'

urlpatterns = [
    path(r'login/', views.LoginView.as_view(), name='login'),
    path(r'register', views.RegisterView.as_view(), name='register'),
    path(r'register/dynamic', views.register, name='dynamic_registration'),
    path(r'register/canvas_config.json', views.canvas_config_json, name='canvas_config_json'),
    path(r'launch/', views.LaunchView.as_view(), name='launch'),
    path(r'jwks/', views.JWKSView.as_view(), name='jwks'),
    path(r'launch/teacher/<str:launch_id>', views.TeacherLaunchView.as_view(), name='teacher_launch'),
    path(r'launch/student/<str:launch_id>', views.StudentLaunchView.as_view(), name='student_launch'),
]

material/urls.py
from . import views
from django.urls import path, include

app_name = 'material'

urlpatterns = [
    path(r'new/',
        views.CreatePackageView.as_view(),
        name='new'
    ),

    path(r'git-clone/',
        views.CreatePackageFromGitView.as_view(),
        name='git_clone'
    ),

    path(r'package/<uuid:pk>/',
        views.ViewPackageView.as_view(),
        name='view'
    ),

    path(r'package/<uuid:pk>.zip',
        views.DownloadOutputView.as_view(),
        name='download_output'
    ),

    path(r'package/<uuid:pk>-source.zip',
        views.DownloadSourceView.as_view(),
        name='download_source'
    ),

    path(r'package/<uuid:pk>/delete',
        views.DeleteView.as_view(),
        name='delete'
    ),

    path(r'package/<uuid:pk>/upload',
        views.UploadFilesView.as_view(),
        name='upload'
    ),

    path(r'package/<uuid:pk>/file/',
        views.FileView.as_view(),
        name='file_root'
    ),

    path(r'package/<uuid:pk>/file/<path:path>',
        views.FileView.as_view(),
        name='file'
    ),

    path(r'package/<uuid:pk>/delete-file/<path:path>',
        views.DeleteFileView.as_view(),
        name='delete_file'
    ),

    path(r'package/<uuid:pk>/configure',
        views.ConfigView.as_view(),
        name='configure'
    ),

    path(r'package/<uuid:pk>/git/update',
        views.UpdateFromGitView.as_view(),
        name='git_update'
    ),

    path(r'package/<uuid:pk>/git/configure',
        views.ConfigureGitView.as_view(),
        name='git_configure'
    ),

    path(r'package/<uuid:pk>/git/webhook',
        views.GitWebhookView.as_view(),
        name='git_webhook'
    ),

    path(r'package/<uuid:pk>/build',
        views.BuildView.as_view(),
        name='build'
    ),

    path(r'package/<uuid:package_pk>/build/<int:pk>',
        views.BuildProgressView.as_view(),
        name='build_progress'
    ),

    path(r'deep-link/<str:launch_id>/',
        views.DeepLinkView.as_view(),
        name='deep_link'
    ),

    path(r'deep-link/<str:launch_id>/package/<uuid:pk>/build',
        views.DeepLinkBuildPackageView.as_view(),
        name='deep_link_build'
    ),
]

material/forms.py
from   .models import ChirunPackage
from   django import forms
from   django.core.exceptions import ValidationError
from   django.urls import resolve, Resolver404
from   django.utils.translation import gettext as _
from   multiupload.fields import MultiFileField, MultiMediaField, MultiImageField
from   urllib.parse import urlparse

class UploadPackageForm(forms.ModelForm):
    files = MultiFileField(min_num=1, required=False)

    class Meta:
        model = ChirunPackage
        fields = []

class CreatePackageFromGitForm(forms.ModelForm):
    class Meta:
        model = ChirunPackage
        fields = ['git_url', 'git_username']
        widgets = {
            'git_username': forms.TextInput(attrs={'placeholder': _('A username or access token, if needed')})
        }

class ConfigureGitForm(CreatePackageFromGitForm):
    ref = forms.ChoiceField(required=False, label=_('Branch'))

DEEP_LINK_TYPES = [
    ('ltiResourceLink', _('Link')),
    ('html', _('Embedded frame')),
]


class DeepLinkForm(forms.Form):
    package = forms.ModelChoiceField(queryset=ChirunPackage.objects.all())
    item = forms.CharField(required=False)
    theme = forms.CharField(required=False)
    item_format = forms.CharField(required=False)
    link_type = forms.ChoiceField(required=False, label=_('Link type'), choices = DEEP_LINK_TYPES)

    def __init__(self, *args, **kwargs):
        link_type_choices = kwargs.pop('link_type_choices')

        super().__init__(*args, **kwargs)

        self.fields['link_type'].choices = link_type_choices

class DeepLinkImportForm(forms.Form):
    url = forms.CharField(required=True)

    def clean(self):
        cleaned_data = super().clean()

        if 'url' not in cleaned_data:
            return

        url = cleaned_data['url']

        path = urlparse(url).path

        try:
            m = resolve(path)
        except Resolver404:
            raise ValidationError(_("This URL is not valid."))
        if not ('material' in m.namespaces and 'pk' in m.kwargs):
            raise ValidationError(_("This is not a package URL."))

        pk = m.kwargs['pk']

        try:
            self.cleaned_data['package'] = ChirunPackage.objects.get(edit_uid = pk)
        except ChirunPackage.DoesNotExist:
            raise ValidationError(_("This is not a valid package URL."))

class PackageFileForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea, required=False)
    replace_file = forms.FileField(required = False)
    path = forms.CharField()

    class Meta:
        model = ChirunPackage
        fields = []

class DeleteFileForm(forms.ModelForm):
    class Meta:
        model = ChirunPackage
        fields = []

class ConfigForm(forms.ModelForm):
    config = forms.JSONField(widget=forms.HiddenInput)

    class Meta:

        model = ChirunPackage
        fields = []

material/views.py
from   . import forms
from   .templatetags.material import urljoin
from   .models import ChirunPackage, Compilation, PackageLTIUse
from   chirun_lti.mixins import BackPageMixin, HelpPageMixin
from   dataclasses import dataclass
from   django.conf import settings
from   django.contrib import messages
from   django.contrib.auth.mixins import UserPassesTestMixin
from   django.core.exceptions import PermissionDenied
from   django.db.models import Q
from   django.http import HttpResponse, HttpResponseRedirect, Http404, HttpResponseBadRequest
from   django.template.loader import get_template
from   django.views import generic
from   django.shortcuts import render, redirect
from   django.urls import reverse, reverse_lazy
from   django.utils.crypto import constant_time_compare
from   django.utils.translation import gettext as _
import hmac
import json
from   lti.views import CachedLTIView
import mimetypes
from   pathlib import Path
from   pylti1p3.deep_link_resource import DeepLinkResource
import shutil
import zipfile

class DeepLinkView(generic.View):
    def dispatch(self, request, *args, **kwargs):
        def respond(view):
            return view(request, *args, **kwargs)

        if request.method.lower() == 'post' and 'url' not in self.request.POST:
                return respond(DeepLinkConfirmView.as_view())

        if 'package' not in self.request.GET:
            return respond(DeepLinkPickPackageView.as_view())

        package = ChirunPackage.objects.get(uid=self.request.GET['package'])

        if package.build_status() != 'built':
            return redirect(reverse('material:deep_link_build', kwargs={'launch_id': kwargs['launch_id'], 'pk': package.uid}))

        if 'theme' not in self.request.GET:
            themes = package.themes()
            if len(themes) == 1:
                return redirect(reverse('material:deep_link', args=(kwargs['launch_id'],))+f'''?package={package.uid}&theme={themes[0]['path']}''')
            else:
                return respond(DeepLinkPickThemeView.as_view())
        if 'item' not in self.request.GET:
            return respond(DeepLinkPickItemView.as_view())

        return respond(DeepLinkConfirmView.as_view())


class AbstractDeepLinkView:
    def dispatch(self, request, *args, **kwargs):
        package_uid = self.request.GET.get('package', self.kwargs.get('pk'))

        if package_uid is not None:
            self.package = ChirunPackage.objects.get(uid=package_uid)

        if not self.get_message_launch().is_deep_link_launch():
            return HttpResponseForbidden('Must be a deep link!')

        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        if hasattr(self, 'package'):
            context['package'] = self.package

        return context


class DeepLinkPickPackageView(AbstractDeepLinkView, CachedLTIView, generic.FormView):
    """
        During a deep link launch, pick the package to use.
        The next step is to pick a theme, if there's more than one, or to pick an item in the package.
    """
    template_name = 'package/deep_link/pick_package.html'
    context_object_name = 'packages'

    form_class = forms.DeepLinkImportForm

    def get_launch_id(self):
        return self.kwargs['launch_id']

    def form_valid(self, form):

        package = form.cleaned_data['package']

        PackageLTIUse.objects.get_or_create(package = package, lti_context = self.get_lti_context())

        return redirect(reverse('material:deep_link', kwargs={'launch_id': self.get_launch_id()})+'?package='+str(package.uid))

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        queryset = ChirunPackage.objects.all()

        same_context = queryset.filter(lti_uses__lti_context=self.get_lti_context()).distinct()

        context['same_context'] = same_context

        return context

    def get_queryset(self):
        return ChirunPackage.objects.all()

class DeepLinkBuildPackageView(AbstractDeepLinkView, BackPageMixin, CachedLTIView, generic.TemplateView):
    """
        During a deep link, after picking a package that hasn't been built or is in the middle of being built, show a holding message.
    """

    template_name = 'package/deep_link/build_package.html'

    def get_back_url(self):
        return reverse_lazy('material:deep_link', kwargs={'launch_id': self.kwargs['launch_id']})


class DeepLinkPickThemeView(AbstractDeepLinkView, BackPageMixin, CachedLTIView, generic.TemplateView):
    """
        During a deep link launch, pick the theme to use in the chosen package.
    """
    template_name = 'package/deep_link/pick_theme.html'

    def get_back_url(self):
        return reverse_lazy('material:deep_link', kwargs=self.kwargs)

class DeepLinkPickItemView(DeepLinkPickThemeView):
    """
        During a deep link launch, pick the item within the previously-chosen package to use.
    """
    template_name = 'package/deep_link/pick_item.html'

    def get_back_url(self):
        url = reverse_lazy('material:deep_link', kwargs=self.kwargs)

        if len(self.package.themes()) > 1:
            url += f'''?package={self.package.uid}'''
        
        return url

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        theme_path = self.request.GET['theme']
        context['theme'] = next(t for t in self.package.themes() if t['path'] == theme_path)

        return context

class DeepLinkConfirmView(AbstractDeepLinkView, BackPageMixin, CachedLTIView, generic.FormView):
    form_class = forms.DeepLinkForm
    template_name = 'package/deep_link/confirm.html'

    def dispatch(self, request, *args, **kwargs):
        self.package = ChirunPackage.objects.get(uid=self.request.GET['package'])

        return super().dispatch(request, *args, **kwargs)

    def get_back_url(self):
        theme = self.request.GET['theme']
        return reverse_lazy('material:deep_link', kwargs=self.kwargs)+f'''?package={self.package.uid}&theme={theme}'''

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()

        deep_link = self.get_message_launch().get_deep_link()
        accept_types = deep_link.get_accept_types()

        kwargs['link_type_choices'] = [(v,label) for v,label in forms.DEEP_LINK_TYPES if v in accept_types]

        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['package'] = self.package
        theme_path = self.request.GET['theme']
        context['theme'] = next(t for t in self.package.themes() if t['path'] == theme_path)

        item_url = context['item_url'] = self.request.GET['item']
        item = context['item'] = self.package.get_item_by_url(item_url)

        context['formats'] = [f for f in item.get('formats',[]) if f['filetype'] == 'html']

        return context

    def form_valid(self, form):
        launch_url = self.request.build_absolute_uri(reverse('lti:launch'))

        package = form.cleaned_data.get('package')
        item_url = form.cleaned_data.get('item')
        theme = self.request.GET.get('theme')
        item_format = form.cleaned_data.get('item_format', 'default')
        link_type = form.cleaned_data.get('link_type', 'ltiResourceLink')

        item = package.get_item_by_url(item_url)

        title = item.get('title',_('Untitled item'))

        if item_format is not None:
            try:
                format_manifest = next(f for f in item['formats'] if f['format'] == item_format)
            except StopIteration:
                raise Exception(f"This item isn't available in the format \"{item_format}\"")

            item_url = format_manifest['url']

        resource = DeepLinkResource()\
            .set_type(link_type)\
            .set_custom_params({
                'package': str(package.uid),
                'item': item_url,
                'theme': theme,
                'item_format': item_format,
            })\
            .set_title(title)

        if link_type == 'ltiResourceLink':
            resource = resource\
                .set_url(launch_url)

        if link_type == 'html':
            absolute_url = self.request.build_absolute_uri(urljoin(package.get_output_url(), item_url))
            template = get_template('package/deep_link/embed_fragment.html')
            resource = resource\
                .set_html(template.render({'absolute_url': absolute_url, 'title': title, package: package}))

        html = self.message_launch.get_deep_link().output_response_form([resource])
        return HttpResponse(html)

class PackageEditView(UserPassesTestMixin):
    """
        A mixin for any view whose object is a ChirunPackage and which requires edit access.
    """
    model = ChirunPackage
    context_object_name = 'package'

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()

        queryset = queryset.filter(edit_uid = self.kwargs.get(self.pk_url_kwarg))

        try:
            obj = queryset.get()
        except queryset.model.DoesNotExist:
            raise Http404(
                _("No %(verbose_name)s found matching the query")
                % {"verbose_name": queryset.model._meta.verbose_name}
            )
        return obj
    
    def test_func(self):
        if self.request.user.is_superuser:
            return True

        return True

    def get_back_url(self):
        return reverse_lazy('material:view', args=(str(self.get_object().edit_uid),))

class DeleteView(PackageEditView, generic.DeleteView):
    model = ChirunPackage
    template_name = 'package/delete.html'

    def get_success_url(self):
        return reverse('index')

class PackageUploadView(PackageEditView):
    form_class = forms.UploadPackageForm

    def form_valid(self, form):
        package = self.object = form.save()

material/templates/package/deep_link/build_package.html
{% extends "package/base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% translate "Building a package" %} - {{block.super}}{% endblock title %}

{% block body_class %}deep-link build-package{% endblock body_class %}
{% block body_attributes %}data-build-status="{{package.build_status}}"{% endblock body_attributes %}

{% block head %}
    {{block.super}}
    {{package.uid|json_script:"package_uid"}}
    <script type="module" src="{% static 'package/deep_link_build_package.mjs' %}"></script>
{% endblock head %}

{% block main %}
    <section data-build-status="not_built">
        <p>{% blocktranslate %}This package has not been built yet. Please build it to continue.{% endblocktranslate %}</p>
    </section>
    <section data-build-status="built">
        <p>{% blocktranslate %}This package has been successfully built.{% endblocktranslate %}</p>
        <p><a href="{% url 'material:deep_link' launch_id %}?package={{package.uid}}">{% translate "Pick an item to use" %}</a>.</p>
    </section>
    <section data-build-status="building">
        <p>{% blocktranslate %}This package is being built. Please wait.{% endblocktranslate %}</p>
    </section>
    <section data-build-status="error">
        <p>{% blocktranslate %}There was an error building this package. Please fix the problem and build it again.{% endblocktranslate %}</p>
    </section>

    {% include "package/deep_link/edit_package.html" %}
{% endblock main %}

material/templates/package/deep_link/confirm.html
{% extends "package/base.html" %}
{% load i18n %}
{% load material %}
{% load static %}

{% block head %}
    {{block.super}}

    {{package.get_output_url|urljoin:theme.path|json_script:"output_root_url"}}

    <script src="{% static 'package/deep_link_confirm.mjs' %}" type="module"></script>
{% endblock head %}

{% block title %}{% translate "Pick an item" %} - {{block.super}}{% endblock title %}

{% block body_class %}deep-link confirm-deep-link two-column{% endblock body_class %}

{% block main %}
    <div id="form">
        {{form.errors}}
        <form method="POST">
            <input type="hidden" name="package" value="{{package.uid}}">
            <input type="hidden" name="theme" value="{{theme.path}}">
            <input type="hidden" name="item" value="{{item_url}}">

            <p>{% blocktranslate with theme=theme.title %}Using the theme <strong>{{theme}}</strong>.{% endblocktranslate %}</p>

            <p>{% blocktranslate with item=item.title %}Using the item <strong>{{item}}</strong>.{% endblocktranslate %}</p>

            {% if formats|length > 1 %}
                <label for="id_item_format">{% translate "Format" %}</label>
                <select name="item_format" id="id_item_format">
                    {% for format in formats %}
                    <option value="{{format.format}}" data-url="{{format.url}}">{{format.format|title}}</option>
                    {% endfor %}
                </select>
            {% else %}
                {% for format in formats %}
                    <input type="hidden" name="item_format" value="{{format.format}}">
                {% endfor %}
            {% endif %}

            {% if form.fields.link_type.choices|length > 1 %}
                {{form.link_type.label}}
                {{form.link_type}}
            {% else %}
                <input type="hidden" name="link_type" value="{{form.fields.link_type.choices.0.0}}">
            {% endif %}

            <p><button type="Submit">{% translate "Use this choice" %}</button></p>

            <p><a href="{{back_url}}">{% translate "Choose something else" %}</a></p>
        </form>

        {% include "package/deep_link/edit_package.html" %}
    </div>

    <div id="preview">
        <h2>{% translate "Preview" %}</h2>
        <iframe src="{{package.get_output_url|urljoin:theme.path|urljoin:item.url}}"></iframe>
    </div>
{% endblock main %}

material/templates/package/deep_link/edit_package.html
{% load i18n %}
<hr>
<p><a target="_blank" href="{% url 'material:view' package.edit_uid %}">{% translate "Edit or build this package" %}</a>.</p>

material/templates/package/deep_link/embed_fragment.html
<div class="chirun-embed">
<p><a href="{{absolute_url}}" target="_blank">{{title}}</a></p>
<iframe src="{{absolute_url}}" width="600" height="600" style="width: 600px; height: 600px"></iframe>
</div>

material/templates/package/deep_link/package_error.html
{% extends "package/base.html" %}
{% load i18n %}

{% block title %}{% translate "There was an error building this package" %} - {{block.super}}{% endblock title %}

{% block body_class %}deep-link package-error{% endblock body_class %}

{% block main %}
    <p>{% translate "There was an error building this package." %}</p>
{% endblock %}

material/templates/package/deep_link/packages.html
{% load i18n %}
<ul>
    {% for package in packages %}
    <li class="package" data-build-status="{{package.build_status}}" data-package-uid="{{package.uid}}">
        <a href="?package={{package.uid}}">{{package.title}}</a>
        <span class="building-message">{% translate "Building" %}</span>
        <span class="error-message">{% translate "Compilation error" %}</span>
    </li>
    {% endfor %}
</ul>

material/templates/package/deep_link/pick_item.html
{% extends "package/base.html" %}
{% load i18n %}

{% block title %}{% translate "Pick an item" %} - {{block.super}}{% endblock title %}

{% block body_class %}deep-link{% endblock body_class %}

{% block main %}
    <p>{% blocktranslate with theme=theme.title %}Using the theme <strong>{{theme}}</strong>.{% endblocktranslate %}</p>

    <p>{% translate "Pick the item that this link will open." %}</p>

    <ul class="package-structure">
    {% for item in package.structure %}
        {% include "package/deep_link/structure_item.html" %}
    {% endfor %}
    </ul>

    {% include "package/deep_link/edit_package.html" %}
{% endblock main %}

material/templates/package/deep_link/pick_package.html
{% extends "package/base.html" %}
{% load i18n %}
{% load static %}

{% block title %}{% translate "Pick a package to use" %}{% endblock title %}

{% block page_title %}{% translate "Pick a package to use" %}{% endblock page_title %}

{% block body_class %}deep-link pick-package{% endblock body_class %}

{% block head %}
    {{block.super}}
    <script type="module" src="{% static 'package/deep_link_pick_package.mjs' %}"></script>
{% endblock head %}

{% block main %}
    {% if same_context.exists %}
    <section id="same-context">
        {% with packages=same_context %}{% include "package/deep_link/packages.html" %}{% endwith %}
    </section>
    {% endif %}

    <section id="new-package">
        <p>{% translate "Or" %}</p>
        <ul>
            <li><a href="{% url 'material:new' %}?launch_id={{message_launch.get_launch_id}}">{% translate "Create a new package" %}</a>.</li>
            <li>
                <p>{% translate "Import a package from another context by URL" %}</p>
                <form method="POST">
                    <label for="import-url">{% translate "Package URL:" %}</label>
                    <input id="import-url" type="text" name="url">
                    <button type="submit">{% translate "Import to this context" %}</button>
                    {% for error in form.non_field_errors %}
                    <div class="form-error">{{error}}</div>
                    {% endfor %}
                    {% for error in form.errors.url %}
                        <div class="form-error">{% translate "Package URL:" %} {{error}}</div>
                    {% endfor %}
                </form>
            </li>
        </ul>
    </section>
{% endblock main %}

material/templates/package/deep_link/pick_theme.html
{% extends "package/base.html" %}
{% load i18n %}

{% block title %}{% translate "Pick a theme" %} - {{block.super}}{% endblock title %}

{% block body_class %}deep-link{% endblock body_class %}

{% block main %}
{{form.errors}}
    <p>{% blocktranslate %}This package offers more than one theme. Pick a theme to use for this link.{% endblocktranslate %}</p>

    <ul>
        {% for theme in package.themes %}
        <li>
            <a href="?package={{package.uid}}&theme={{theme.path}}">{{theme.title}}</a>
        </li>
        {% endfor %}
    </ul>

    {% include "package/deep_link/edit_package.html" %}
{% endblock main %}

material/templates/package/deep_link/structure_item.html
{% load i18n %}
{% load material %}
<li>
    <a href="?package={{package.uid}}&theme={{theme.path}}&item={{item.url}}">{{item.title}}</a>

    {% if item.content %}
    <ul>
        {% for subitem in item.content %}
        {% include "package/deep_link/structure_item.html" with item=subitem %}
        {% endfor %}
    </ul>
    {% endif %}
</li>