chirun_lti/urls.py
from   django.conf import settings
from   django.conf.urls.static import static
from   django.contrib import admin
from   django.urls import path, include
from   django.utils.translation import gettext_lazy as _
import lti.views

urlpatterns = [
    path('', lti.views.IndexView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path('lti/', include('lti.urls', namespace='lti')),
    path('material/', include('material.urls', namespace='material')),
]

admin.site.site_header = admin.site.site_title = admin.site.index_title = _('Chirun LTI Administration')

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lti/urls.py
from . import views
from django.urls import path, include

app_name = 'lti'

urlpatterns = [
    path(r'login/', views.LoginView.as_view(), name='login'),
    path(r'register', views.RegisterView.as_view(), name='register'),
    path(r'register/dynamic', views.register, name='dynamic_registration'),
    path(r'register/canvas_config.json', views.canvas_config_json, name='canvas_config_json'),
    path(r'launch/', views.LaunchView.as_view(), name='launch'),
    path(r'jwks/', views.JWKSView.as_view(), name='jwks'),
    path(r'launch/teacher/<str:launch_id>', views.TeacherLaunchView.as_view(), name='teacher_launch'),
    path(r'launch/student/<str:launch_id>', views.StudentLaunchView.as_view(), name='student_launch'),
]

material/urls.py
from . import views
from django.urls import path, include

app_name = 'material'

urlpatterns = [
    path(r'new/',
        views.CreatePackageView.as_view(),
        name='new'
    ),

    path(r'git-clone/',
        views.CreatePackageFromGitView.as_view(),
        name='git_clone'
    ),

    path(r'package/<uuid:pk>/',
        views.ViewPackageView.as_view(),
        name='view'
    ),

    path(r'package/<uuid:pk>.zip',
        views.DownloadOutputView.as_view(),
        name='download_output'
    ),

    path(r'package/<uuid:pk>-source.zip',
        views.DownloadSourceView.as_view(),
        name='download_source'
    ),

    path(r'package/<uuid:pk>/delete',
        views.DeleteView.as_view(),
        name='delete'
    ),

    path(r'package/<uuid:pk>/upload',
        views.UploadFilesView.as_view(),
        name='upload'
    ),

    path(r'package/<uuid:pk>/file/',
        views.FileView.as_view(),
        name='file_root'
    ),

    path(r'package/<uuid:pk>/file/<path:path>',
        views.FileView.as_view(),
        name='file'
    ),

    path(r'package/<uuid:pk>/delete-file/<path:path>',
        views.DeleteFileView.as_view(),
        name='delete_file'
    ),

    path(r'package/<uuid:pk>/configure',
        views.ConfigView.as_view(),
        name='configure'
    ),

    path(r'package/<uuid:pk>/git/update',
        views.UpdateFromGitView.as_view(),
        name='git_update'
    ),

    path(r'package/<uuid:pk>/git/configure',
        views.ConfigureGitView.as_view(),
        name='git_configure'
    ),

    path(r'package/<uuid:pk>/git/webhook',
        views.GitWebhookView.as_view(),
        name='git_webhook'
    ),

    path(r'package/<uuid:pk>/build',
        views.BuildView.as_view(),
        name='build'
    ),

    path(r'package/<uuid:package_pk>/build/<int:pk>',
        views.BuildProgressView.as_view(),
        name='build_progress'
    ),

    path(r'deep-link/<str:launch_id>/',
        views.DeepLinkView.as_view(),
        name='deep_link'
    ),

    path(r'deep-link/<str:launch_id>/package/<uuid:pk>/build',
        views.DeepLinkBuildPackageView.as_view(),
        name='deep_link_build'
    ),
]

material/models.py
from   channels.layers import get_channel_layer
import configparser
from   django.conf import settings
from   django.contrib import admin
from   django.db import models
from   django.db.models import F, Max, OuterRef, Subquery
from   django.urls import reverse
from   django.utils.translation import gettext as _
from   django.utils import timezone
import functools
import json
from   lti.models import Context, ResourceLink
import os
from   pathlib import Path, PurePath
from   pylti1p3.contrib.django.lti1p3_tool_config.models import LtiTool
import subprocess
import urllib.parse
import uuid
import yaml



def all_files_relative_to(top):
    for d,dirs,files in os.walk(str(top)):
        rd = Path(d).relative_to(top)
        for f in sorted(files, key=str):
            yield str(rd / f)

GIT_STATUSES = [
    ("cloning", _("Cloning from the source repository.")),
    ("updating", _("Updating from the source repository.")),
    ("ready", _("Ready to use")),
    ("error", _("There was an error fetching from the source repository."))
]

class GitException(Exception):
    pass

class ChirunPackageManager(models.Manager):
    def get_queryset(self):
        latest_compilations = Compilation.objects.filter(package=OuterRef('uid')).order_by('-start_time')
        
        queryset = super().get_queryset() \
            .annotate(last_compiled = Max("compilations__start_time")) \
            .annotate(last_launched = Max("launches__launch_time")) \
            .annotate(last_build_status = Subquery(latest_compilations.values('status')[:1]))

        return queryset

class ChirunPackage(models.Model):
    objects = ChirunPackageManager()

    name = models.CharField(max_length=500)
    author = models.CharField(max_length=200, blank=True, null=True)
    uid = models.UUIDField(default = uuid.uuid4, primary_key = True)
    edit_uid = models.UUIDField(default = uuid.uuid4, unique = True)

    created = models.DateTimeField(auto_now_add = True)

    git_url = models.CharField(max_length=2000, default='', blank=True, verbose_name=_('Git URL'))
    git_username = models.CharField(max_length=200, default='', blank=True, verbose_name=_('Username'))
    git_status = models.CharField(max_length=10, default='cloning', choices=GIT_STATUSES)

    def __str__(self):
        return f'{self.name} ({self.uid})'

    class Meta:
        ordering = (models.functions.Lower('name'), '-created', 'uid')


    @property
    def source_type(self):
        if self.git_url:
            return 'git'

        return 'local'

    @staticmethod
    def channel_group_name_for_package(uid):
        return f'package_{uid}'

    def get_channel_group_name(self):
        return ChirunPackage.channel_group_name_for_package(self.uid)

    @property
    def title(self):
        return self.manifest.get('title', self.name if self.name else _("Unnamed package"))

    @property 
    def relative_extracted_path(self):
        if self.uid is None:
            raise Exception(_("This object doesn't have an ID yet."))
        path = Path('chirun-packages') / 'source' / str(self.uid)
        return path

    @property
    def absolute_extracted_path(self):
        path = Path() / settings.MEDIA_ROOT / self.relative_extracted_path
        path.mkdir(exist_ok=True, parents=True)
        return path.resolve()

    @property 
    def relative_output_path(self):
        if self.uid is None:
            raise Exception(_("This object doesn't have an ID yet."))
        path = Path('chirun-packages') / 'output' / str(self.uid)
        return path

    @property
    def absolute_output_path(self):
        path = Path() / settings.MEDIA_ROOT / self.relative_output_path
        path.mkdir(exist_ok=True, parents=True)
        return path.resolve()

    def has_output(self):
        return (self.absolute_output_path / 'MANIFEST.json').exists()

    def build(self):
        compilation = Compilation.objects.create(package = self)

        from . import tasks
        tasks.build_package(compilation)

        return compilation
        
    def run_git_command(self, cmd, save_interaction=False):
        cmd = [str(x) for x in cmd]
        if save_interaction:
            git_interaction = GitInteraction.objects.create(package = self, command = ' '.join(cmd))
        result = subprocess.run(cmd, cwd=self.absolute_extracted_path, env={'GIT_CEILING_DIRECTORIES': str(self.absolute_extracted_path.parent)}, capture_output=True, encoding='utf-8')

        if save_interaction:
            try:
                result.check_returncode()
                git_interaction.status = 'success'
            except subprocess.CalledProcessError:
                git_interaction.status = 'error'

            git_interaction.output = result.stdout + ('\n' if result.stdout and result.stderr else '') + result.stderr

            git_interaction.save(update_fields=('status', 'output'))

        try:
            result.check_returncode()
        except subprocess.CalledProcessError as e:
            raise GitException(e)

        return result

    def clone_from_git(self, ref=None):
        self.git_status = 'cloning'
        self.save(update_fields=('git_status',))

        from . import tasks
        tasks.clone_from_git(self, ref=ref)

    @property
    def git_remote_url(self):
        pr = urllib.parse.urlparse(self.git_url)
        scheme, netloc, path, params, query, fragment = pr
        netloc = f'{self.git_username}@{pr.hostname}' if self.git_username else pr.netloc
        return urllib.parse.urlunparse((scheme, netloc, path, params, query, fragment))

    def update_from_git(self, ref=None):
        from . import tasks

        self.git_status = 'updating'
        self.save(update_fields=('git_status',))

        git_config = self.absolute_extracted_path / '.git' / 'config'
        if not git_config.exists():
            self.clone_from_git(ref=ref)

        cp = configparser.ConfigParser()
        cp.read(git_config)
        try:
            remote_url = cp.get('remote "origin"', 'url')
        except configparser.NoSectionError:
            remote_url = None
        if self.git_remote_url != remote_url:
            self.clone_from_git()

        tasks.update_from_git(self, ref=ref)

    def git_current_branch(self):
        if self.git_status != 'ready':
            return

        try:
            with open(self.absolute_extracted_path / '.git' / 'HEAD') as f:
                ref = f.read().strip()
        except FileNotFoundError:
            return

        if ref[:5] != 'ref: ':
            return

        return PurePath(ref[5:]).name

    def git_last_commit(self):
        if self.git_status != 'ready':
            return


        try:
            result = self.run_git_command(['git','log','--format=format:%h%x09%s','-n','1']).stdout.strip()
            i = result.index('\t')
        except (GitException, ValueError):
            return
        commit_hash = result[:i]
        commit_message = result[i+1:]
        return commit_hash, commit_message

    def git_branches(self):
        if self.git_status != 'ready':
            return

        try:
            result = self.run_git_command(['git','branch','-a', '--no-color'])
        except GitException:
            return

        branches = set()
        current = None
        for line in result.stdout.split('\n'):
            if not line:
                continue

            current = line[0] == '*'

            ref = line[2:].split(' ')[0]
            if '(' in ref or 'HEAD' in ref:
                continue

            ref = PurePath(ref)
            branches.add(ref.name)

        return sorted(branches)

    def get_absolute_url(self):
        return reverse('material:view', args=(self.edit_uid,))

    def get_output_url(self):
        return PurePath(settings.MEDIA_URL) / self.relative_output_path

    def get_index_url(self):
        return self.get_output_url() / 'index.html'

    def build_status(self):
        last_build = self.compilations.first()
        if last_build:
            return last_build.status
        else:
            return 'not_built'

    def get_config(self):
        try: 
            with open(self.absolute_extracted_path / 'config.yml') as f:
                return yaml.load(f, Loader=yaml.CLoader)
        except FileNotFoundError:
            pass

    def save_config(self, config):
        with open(self.absolute_extracted_path / 'config.yml', 'w') as f:
            f.write(yaml.dump(config))

    def create_initial_config(self):
        structure = []

        config = {
            'structure': structure
        }

        root = self.absolute_extracted_path

        source_files = [p for p in root.rglob('*') if p.suffix in ('.tex', '.md')]

        is_standalone = len(source_files) == 1

        for p in source_files:
            if p.suffix not in ('.tex','.md'):
                continue

            structure.append({
                'source': str(p.relative_to(root)),
                'title': p.name,
                'type': 'standalone' if is_standalone else 'chapter',
            })

        self.save_config(config)
        return config

    @property
    def manifest(self):
        try:
            manifest = self.absolute_output_path / 'MANIFEST_hidden.json'
            if not manifest.exists():
                manifest = self.absolute_output_path / 'MANIFEST.json'
            with open(manifest) as f:
                data = json.load(f)
            return data
        except FileNotFoundError:
            return {}

    @property
    def structure(self):
        return self.manifest.get('structure')

    def all_items(self):
        """
            A generator for all items in the package's structure, in depth-first order.
        """

        def visit(item):
            yield item
            for subitem in item.get('content',[]):
                yield from visit(subitem)

        for item in self.structure:
            yield from visit(item)

    def get_item_by_url(self, item_url):

material/forms.py
from   .models import ChirunPackage
from   django import forms
from   django.core.exceptions import ValidationError
from   django.urls import resolve, Resolver404
from   django.utils.translation import gettext as _
from   multiupload.fields import MultiFileField, MultiMediaField, MultiImageField
from   urllib.parse import urlparse

class UploadPackageForm(forms.ModelForm):
    files = MultiFileField(min_num=1, required=False)

    class Meta:
        model = ChirunPackage
        fields = []

class CreatePackageFromGitForm(forms.ModelForm):
    class Meta:
        model = ChirunPackage
        fields = ['git_url', 'git_username']
        widgets = {
            'git_username': forms.TextInput(attrs={'placeholder': _('A username or access token, if needed')})
        }

class ConfigureGitForm(CreatePackageFromGitForm):
    ref = forms.ChoiceField(required=False, label=_('Branch'))

DEEP_LINK_TYPES = [
    ('ltiResourceLink', _('Link')),
    ('html', _('Embedded frame')),
]


class DeepLinkForm(forms.Form):
    package = forms.ModelChoiceField(queryset=ChirunPackage.objects.all())
    item = forms.CharField(required=False)
    theme = forms.CharField(required=False)
    item_format = forms.CharField(required=False)
    link_type = forms.ChoiceField(required=False, label=_('Link type'), choices = DEEP_LINK_TYPES)

    def __init__(self, *args, **kwargs):
        link_type_choices = kwargs.pop('link_type_choices')

        super().__init__(*args, **kwargs)

        self.fields['link_type'].choices = link_type_choices

class DeepLinkImportForm(forms.Form):
    url = forms.CharField(required=True)

    def clean(self):
        cleaned_data = super().clean()

        if 'url' not in cleaned_data:
            return

        url = cleaned_data['url']

        path = urlparse(url).path

        try:
            m = resolve(path)
        except Resolver404:
            raise ValidationError(_("This URL is not valid."))
        if not ('material' in m.namespaces and 'pk' in m.kwargs):
            raise ValidationError(_("This is not a package URL."))

        pk = m.kwargs['pk']

        try:
            self.cleaned_data['package'] = ChirunPackage.objects.get(edit_uid = pk)
        except ChirunPackage.DoesNotExist:
            raise ValidationError(_("This is not a valid package URL."))

class PackageFileForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea, required=False)
    replace_file = forms.FileField(required = False)
    path = forms.CharField()

    class Meta:
        model = ChirunPackage
        fields = []

class DeleteFileForm(forms.ModelForm):
    class Meta:
        model = ChirunPackage
        fields = []

class ConfigForm(forms.ModelForm):
    config = forms.JSONField(widget=forms.HiddenInput)

    class Meta:

        model = ChirunPackage
        fields = []

material/templates/package/base.html
{% extends "lti/base.html" %}
{% load static %}

{% block title %}{% if package %}{{package.title}} - {% endif %}{{block.super}}{% endblock title %}
{% block page_title %}
{{package.title}}{% if package.manifest.code %}<small> - {{package.manifest.code}}</small>{% endif %}{% if package.manifest.year %} <small>({{package.manifest.year}})</small>{% endif %}
{% if package.manifest.author %}
    <br>
    <small>by <strong class="author">{{package.manifest.author}}</strong></small>
{% endif %}
{% endblock page_title %}

material/templates/package/config.html
{% extends "package/base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% translate "Configuring" %} {{block.super}}{% endblock title %}
{% block page_title %}
    {% translate "Configuring" %} <em>{{block.super}}</em>
{% endblock page_title %}


{% block head %}
    <script src="{% static 'package/configure.mjs' %}" type="module"></script>
    {{files|json_script:"files_json"}}
    {{config|json_script:"config_json"}}

    {{block.super}}
{% endblock %}

{% block body_class %}configure-package two-column{% endblock body_class %}

{% block main %}
    <chirun-package-config files="files_json" config="config_json" media-root="{{media_root}}"></chirun-package-config>
{% endblock main %}

material/templates/package/create.html
{% extends "package/base.html" %}

{% load i18n %}

{% block title %}Create a new package - {{block.super}}{% endblock title %}
{% block page_title %}{% translate "Create a new package" %}{% endblock page_title %}

{% block body_class %}{{block.super}} create-package{% endblock %}

{% block main %}
    <nav>
        <p>{% blocktranslate %}How would you like to create this package?{% endblocktranslate %}</p>
        <p id="quick-links">
            <a href="#from-scratch">{% translate "Start from scratch" %}</a>
            <a href="#upload-files">{% translate "Upload files" %}</a>
            <a href="#git-clone">{% translate "Clone a git repository" %}</a>
        </p>
    </nav>

    <hr>

    <div id="forms">
        <section id="from-scratch">
            <h2>{% translate "Start from scratch" %}</h2>
            <form method="POST">
                <p><button class="action" type="submit">{% translate "Create a new package" %}</button></p>
            </form>
        </section>

        <hr>

        <section id="upload-files">
            <h2>{% translate "Upload files" %}</h2>
            <form method="POST" enctype="multipart/form-data">
                <p class="input-hint">{% blocktranslate %}If you already have source files, upload them, either separately or in a .zip file.{% endblocktranslate %}</p>
                <div class="form-columns">
                    {{form}}
                </div>
                
                <p><button class="action" type="submit">{% translate "Upload" %}</button></p>
            </form>
        </section>

        <hr>

        <section id="git-clone">
            <h2>{% translate "Clone a git repository" %}</h2>
            <form action="{% url 'material:git_clone' %}" method="POST">
                <p class="input-hint">{% blocktranslate %}If you store your package's files in a git repository, clone it.{% endblocktranslate %}</p>
                <div class="form-columns">
                    {{git_form}}
                </div>
                
                <p><button class="action" type="submit">{% translate "Clone from git" %}</button></p>
            </form>
        </section>
    </div>
{% endblock main %}

material/templates/package/deep_link_packages.html
{% load i18n %}
<ul>
    {% for package in packages %}
    <li class="package" data-build-status="{{package.build_status}}" data-package-uid="{{package.uid}}">
        <a href="?package={{package.uid}}">{{package.title}}</a>
        <span class="building-message">{% translate "Building" %}</span>
        <span class="error-message">{% translate "Compilation error" %}</span>
    </li>
    {% endfor %}
</ul>

material/templates/package/deep_link_pick_item.html
{% extends "package/base.html" %}
{% load i18n %}

{% block title %}{% translate "Pick an item" %} - {{block.super}}{% endblock title %}

{% block body_class %}deep-link{% endblock body_class %}

{% block main %}
    {% if package.build_status == 'built' %}
        <p>{% translate "Pick the item that this link will open." %}</p>

        <ul class="package-structure">
        {% for item in package.structure %}
            {% include "package/deep_link_structure_item.html" %}
        {% endfor %}
        </ul>

    {% elif package.build_status == 'building' %}
        <p>{% translate "This package is being built." %}</p>
        <a href="{% url 'material:deep_link' message_launch.get_launch_id %}?package={{package.uid}}">{% translate "Reload" %}</a>
    {% elif package.build_status == 'error' %}
        <p>{% translate "There was an error building this package." %}</p>
    {% endif %}

    <p><a target="_blank" href="{% url 'material:view' package.uid %}">{% translate "Edit this package" %}</a></p>
{% endblock main %}

material/templates/package/deep_link_pick_package.html
{% extends "package/base.html" %}
{% load i18n %}
{% load static %}

{% block title %}{% translate "Pick a package to use" %}{% endblock title %}

{% block page_title %}{% translate "Pick a package to use" %}{% endblock page_title %}

{% block body_class %}deep-link pick-package{% endblock body_class %}

{% block head %}
    {{block.super}}
    <script type="module" src="{% static 'package/deep_link_pick_package.mjs' %}"></script>
{% endblock head %}

{% block main %}
    {% if same_context.exists %}
    <section id="same-context">
        <h2>{% translate "Packages in this context" %}</h2>
        {% with packages=same_context %}{% include "package/deep_link_packages.html" %}{% endwith %}
    </section>
    {% endif %}

    {% if same_tool.exists %}
    <section id="same-tool">
        <h2>{% translate "Packages in other contexts on this platform" %}</h2>
        {% with packages=same_tool %}{% include "package/deep_link_packages.html" %}{% endwith %}
    </section>
    {% endif %}

    {% if other_built.exists %}
    <section id="other-built">
        <h2>{% translate "Other packages" %}</h2>
        {% with packages=other_built %}{% include "package/deep_link_packages.html" %}{% endwith %}
    </section>
    {% endif %}

    <p>{% translate "Or" %} <a href="{% url 'material:new' %}?launch_id={{message_launch.get_launch_id}}">{% translate "upload a new package" %}</a>.</p>
{% endblock main %}

material/templates/package/detail.html
{% extends "package/base.html" %}

{% load i18n %}

{% block body_class %}package-details{% endblock body_class %}

{% block main %}
    <section id="intro">
        <h2>{% translate "Manage this package" %}</h2>

        <p>{% translate "The following URL allows you to edit this package at a later date." %}</p>
        <a id="edit-link" href="{{request.build_absolute_uri}}">{{request.build_absolute_uri}}</a>

    </section>

    <section id="controls">
        <h2>{% translate "Actions" %}</h2>
        <nav>
            <form method="POST" action="{% url 'material:build' package.edit_uid %}">
                <button type="submit">{% translate "Build" %}</button>
            </form>

            {% if package.source_type == 'local' %}
                <a href="{% url 'material:configure' package.edit_uid %}">{% translate "Configure" %}</a>

                <a href="{% url 'material:file_root' package.edit_uid %}">{% translate "View or edit files in this package" %}</a>
            {% elif package.source_type == 'git' %}
                <form method="POST" action="{% url 'material:git_update' package.edit_uid %}">
                    <button type="submit">{% translate "Update from git" %}</button>
                </form>

                <a href="{% url 'material:git_configure' package.edit_uid %}">{% translate "Configure" %}</a>
                
                <a href="{{package.git_url}}">{% translate "View the source repository" %}</a>
            {% endif %}

            <a href="{% url 'material:download_source' package.edit_uid %}">{% translate "Download this package's source files" %}</a>

            <a class="danger" href="{% url 'material:delete' package.edit_uid %}">{% translate "Delete this package" %}</a>
        </nav>
    </section>

    {% if package.source_type == 'git' %}
    <section id="git-info">
        <p>{% blocktranslate %}This package is linked to an external git repository.{% endblocktranslate %}</p>
        <dl>
            <dt>{% translate "Current status" %}</dt>
            <dd>{{package.get_git_status_display}}</dd>
    
            {% if package.git_status == 'ready' %}

            <dt>{% translate "Current branch" %}</dt>
            <dd><code>{{package.git_current_branch}}</code></dd>

            <dt>{% translate "Last commit" %}</dt>
            {% with commit=package.git_last_commit %}
            <dd><a href="{{package.git_url}}/commit/{{commit.0}}"><code>{{commit.1}}</code></a></dd>
            {% endwith %}

            {% endif %}
        </dl>
    </section>
    {% endif %}

    {% if package.build_status == "error" %}
    <section id="build-error">
        <p>{% translate "The last build of this package encountered an error." %}</p>
        <a href="{{package.compilations.first.get_absolute_url}}">{% translate "View the build log." %}</a>
    </section>

    {% elif package.build_status == "building" %}
    <section id="building">
        <p>{% translate "This package is being built." %}</p>
    </section>

    {% elif package.build_status == "not built" %}
    <section id="not-built">
        <p>{% translate "This package has not been built yet." %}</p>
    </section>
    {% endif %}

    {% if package.has_output %}
    <section id="view">
        <h2>{% translate "View this package's content" %}</h2>

        <p><a href="{% url 'material:download_output' package.edit_uid %}">{% translate "Download the generated content as a .zip file" %}</a></p>

        {% if package.themes|length > 1 %}
        <ul class="package-built-themes">
            {% for theme in package.themes %}
            <li>
                <h3>{% blocktranslate with theme=theme.title %}Theme "{{theme}}"{% endblocktranslate %}</h3>
                <ul class="package-structure">
                    {% for item in package.structure %}
                    {% include "package/structure_item.html" %}
                    {% endfor %}
                </ul>
            </li>
            {% endfor %}
        </ul>

        {% else %}
            {% with theme=package.themes.0 %}
                <ul class="package-structure">
                    {% for item in package.structure %}
                    {% include "package/structure_item.html" %}
                    {% endfor %}
                </ul>
            {% endwith %}
        {% endif %}
    </section>
    {% endif %}

    <section id="builds">
        <h2>{% translate "Builds" %}</h2>
        <ol>
            {% for compilation in package.compilations.all|slice:":10" %}
            <li>
                <a href="{{compilation.get_absolute_url}}"><time>{{compilation.start_time|date:"Y-m-d H:i"}}</time> - {{compilation.status}}</a>
            </li>
            {% endfor %}
        </ol>
    </section>
{% endblock main %}

material/templates/package/package_file.html
{% extends "package/base.html" %}
{% load i18n %}

{% load static %}

{% block title %}{{root_relative_path}} - {{block.super}}{% endblock title %}}
{% block page_title %}{% translate "Editing files in" %} <em>{{block.super}}</em>{% endblock page_title %}

{% block body_class %}package-file two-column{{block.super}}{% endblock %}

{% block main_id %}app{% endblock main_id %}
{% block main_class %}{% if path.is_dir %}no-editor{% endif %}{% endblock main_class %}

{% block main %}
    <nav>
        <ul class="breadcrumbs">
            {% for bit in directory.parents reversed %}
            <li><a href="{% url 'material:file' package.edit_uid bit %}">{% if bit == bit.parent %}{{package.title}}{% else %}{{bit.name}}{% endif %}</a></li>
            {% endfor %}
            <li>{% if directory == directory.parent %}{{package.title}}{% else %}{{directory.name}}{% endif %}</li>
        </ul>
        <ul class="siblings">
            {% if directory.parent != directory %}
            <li class="sibling parent directory"><a href="{% url 'material:file' package.edit_uid directory.parent %}">{% if directory.parent.name %}{{directory.parent.name}}{% else %}{% translate "Top level" %}{% endif %}</a></li>
            {% endif %}

            {% for item,is_dir in siblings %}
                <li class="sibling{% if is_dir %} directory{% endif %}" {% if item == root_relative_path %}aria-current="page"{% endif %}>
                    <a href="{% url 'material:file' package.edit_uid item %}">{{item.name}}</a>
                </li>
            {% endfor %}
        </ul>

        <hr>

        <form method="GET" id="newfile-form">
            <label for="newfile">{% translate "New file:" %}</label>
            <input name="newfile" id="newfile">
            <button type="submit">{% translate "Create" %}</button>
        </form>

        <hr>

        <form method="POST" enctype="multipart/form-data" action="{% url 'material:upload' package.edit_uid %}">
            <input type="hidden" name="editing_file" value="{{root_relative_path}}">
            <p class="input-hint">{% blocktranslate %}Upload one or more files, either separately or in a .zip file.{% endblocktranslate %}</p>
            {{upload_form}}
            <button class="action" type="submit">{% translate "Upload" %}</button>
        </form>
    </nav>

    {% if path.is_dir %}
    {% else %}
    <div id="editor">

        <form style="display:none" id="delete-form" method="POST" action="{% url 'material:delete_file' package.edit_uid root_relative_path %}"></form>

        <form method="POST" id="content-form" enctype="multipart/form-data">
            {{form.errors}}
            <div class="controls">
                <label for="id_path">{% translate "Editing" %}</label>
                {{form.path}}
                <button class="action" type="submit">{% translate "Save" %}</button>
                {% if path.exists %}
                    <a download href="{{file_url}}">{% translate "Download this file" %}</a>
                    <button type="button" onclick="document.getElementById('delete-form').submit()" class="delete" type="submit">{% translate "Delete this file" %}</button>
                {% endif %}
                <label for="id_replace_file">{% translate "Replace this file" %}
                {{form.replace_file}}
            </div>

            {% if is_image %}
                <img src="{{file_url}}">
            {% elif is_binary %}
                {% translate "This is a binary file." %}
            {% else %}
                {{form.content}}
            {% endif %}
        </form>
    </div>
    {% endif %}
{% endblock main %}